version: "3.8"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    depends_on:
      - app
    environment:
      NGINX_FPM_HOST: app
      NGINX_ROOT: /usr/src/app/public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-access"
      - "traefik.http.middlewares.freight-management-ratelimit.ratelimit.average=10"
      - "traefik.http.middlewares.freight-management-ratelimit.ratelimit.burst=50"
      - "traefik.http.routers.carisca-innovations-freight-management.rule=Host(`freight-management.cariscainnovations.org`)"
      - "traefik.http.routers.carisca-innovations-freight-management.entrypoints=https"
      - "traefik.http.routers.carisca-innovations-freight-management.tls=true"
      - "traefik.http.routers.carisca-innovations-freight-management.tls.certresolver=le"
      - "traefik.http.routers.carisca-innovations-freight-management.middlewares=freight-management-ratelimit"
      - "traefik.http.services.carisca-innovations-freight-management.loadbalancer.server.port=80"
  db:
    container_name: db
    image: mysql:latest
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: digitalFreight
      MYSQL_ROOT_PASSWORD: digitalFreight
      # MYSQL_USER: root
      # MYSQL_PASSWORD:


  redis:
    container_name: redis
    image: redis:latest
