name: Deploy website and run remote commands
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy and Setup
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: 104.243.32.71
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: 104.243.32.71
        username: apcserv7
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 7522
        script: |
          cd /home/apcserv7/app.daloadmaster.com
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
