name: Deploy website and run remote commands
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy and Setup
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: 104.243.32.71
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /home/apcserv7/app.daloadmaster.com/
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: 104.243.32.71
        username: ${{ secrets.SERVER_SSH_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        port: 7522
        script: |
          echo "Checking PHP version and extensions..."
          php -v
          php -m
          
          echo "Checking if phar extension is installed..."
          if php -m | grep -q phar; then
            echo "phar extension is installed."
          else
            echo "phar extension is not installed. Please contact your hosting provider to install it."
          fi
          
          echo "Checking if xml extension is installed..."
          if php -m | grep -q xml; then
            echo "xml extension is installed."
          else
            echo "xml extension is not installed. Please contact your hosting provider to install it."
          fi
          
          echo "Checking Composer..."
          if command -v composer &>/dev/null; then
            echo "Composer is installed."
            composer --version
          else
            echo "Composer is not installed. Installing locally..."
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php --install-dir=/home/apcserv7/app.daloadmaster.com --filename=composer
            php -r "unlink('composer-setup.php');"
            alias composer="php /home/apcserv7/app.daloadmaster.com/composer"
          fi
          
          cd /home/apcserv7/app.daloadmaster.com
          
          echo "Installing/Updating dependencies..."
          composer install --no-interaction --prefer-dist --optimize-autoloader
          
          echo "Creating Termwind configuration..."
          mkdir -p config
          echo "<?php return ['use_dom_document' => false];" > config/termwind.php
          
          echo "Running Laravel commands..."
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear
          php artisan migrate --force
